import { Event, Ticket, POAP, User } from "./types";

export const mockUsers: User[] = [
  {
    id: "1",
    email: "john@example.com",
    name: "John Doe",
    walletAddress: "0x1234...5678",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john",
    role: "attendee",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    email: "sarah@example.com",
    name: "Sarah Chen",
    walletAddress: "0x8765...4321",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    role: "host",
    createdAt: new Date("2024-01-10"),
  },
];

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Web3 Developer Summit 2024",
    description: "Join the biggest Web3 developer conference of the year. Learn from industry experts, network with fellow builders, and discover the latest in blockchain technology.",
    date: new Date("2024-03-15"),
    time: "09:00",
    location: "San Francisco, CA",
    locationType: "physical",
    bannerImage: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
    hostId: "2",
    hostName: "Sarah Chen",
    maxAttendees: 500,
    registeredCount: 347,
    registrationType: "free",
    poapEnabled: true,
    status: "upcoming",
    contractAddress: "0xabc...def",
    createdAt: new Date("2024-01-20"),
    category: "Conference",
  },
  {
    id: "2",
    title: "Move Language Workshop",
    description: "Deep dive into the Move programming language. Perfect for developers looking to build on Endless Protocol.",
    date: new Date("2024-03-20"),
    time: "14:00",
    location: "Virtual Event",
    locationType: "virtual",
    bannerImage: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800",
    hostId: "2",
    hostName: "Sarah Chen",
    maxAttendees: 200,
    registeredCount: 156,
    registrationType: "free",
    poapEnabled: true,
    status: "upcoming",
    contractAddress: "0xdef...123",
    createdAt: new Date("2024-01-22"),
    category: "Workshop",
  },
  {
    id: "3",
    title: "NFT Art Exhibition",
    description: "Experience the future of art at our exclusive NFT gallery showcase featuring top digital artists from around the world.",
    date: new Date("2024-03-25"),
    time: "18:00",
    location: "New York, NY",
    locationType: "physical",
    bannerImage: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800",
    hostId: "2",
    hostName: "Sarah Chen",
    maxAttendees: 150,
    registeredCount: 150,
    registrationType: "paid",
    price: 50,
    poapEnabled: true,
    status: "upcoming",
    contractAddress: "0x456...789",
    createdAt: new Date("2024-01-25"),
    category: "Exhibition",
  },
  {
    id: "4",
    title: "Blockchain Networking Night",
    description: "Connect with fellow blockchain enthusiasts, developers, and investors in a casual setting.",
    date: new Date("2024-02-28"),
    time: "19:00",
    location: "Austin, TX",
    locationType: "physical",
    bannerImage: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=800",
    hostId: "2",
    hostName: "Sarah Chen",
    maxAttendees: 100,
    registeredCount: 89,
    registrationType: "free",
    poapEnabled: true,
    status: "completed",
    contractAddress: "0x789...abc",
    createdAt: new Date("2024-01-15"),
    category: "Networking",
  },
];

export const mockTickets: Ticket[] = [
  {
    id: "t1",
    eventId: "1",
    eventTitle: "Web3 Developer Summit 2024",
    eventDate: new Date("2024-03-15"),
    eventLocation: "San Francisco, CA",
    eventBanner: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
    ownerId: "1",
    ownerWallet: "0x1234...5678",
    tokenId: "1001",
    isUsed: false,
    qrCode: "QR_TICKET_1001",
    mintedAt: new Date("2024-02-01"),
    transferable: false,
  },
  {
    id: "t2",
    eventId: "2",
    eventTitle: "Move Language Workshop",
    eventDate: new Date("2024-03-20"),
    eventLocation: "Virtual Event",
    eventBanner: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800",
    ownerId: "1",
    ownerWallet: "0x1234...5678",
    tokenId: "2001",
    isUsed: false,
    qrCode: "QR_TICKET_2001",
    mintedAt: new Date("2024-02-05"),
    transferable: false,
  },
  {
    id: "t3",
    eventId: "4",
    eventTitle: "Blockchain Networking Night",
    eventDate: new Date("2024-02-28"),
    eventLocation: "Austin, TX",
    eventBanner: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=800",
    ownerId: "1",
    ownerWallet: "0x1234...5678",
    tokenId: "4001",
    isUsed: true,
    qrCode: "QR_TICKET_4001",
    mintedAt: new Date("2024-02-10"),
    transferable: false,
  },
];

export const mockPOAPs: POAP[] = [
  {
    id: "p1",
    eventId: "4",
    eventTitle: "Blockchain Networking Night",
    eventDate: new Date("2024-02-28"),
    eventLocation: "Austin, TX",
    ownerId: "1",
    ownerWallet: "0x1234...5678",
    tokenId: "POAP_4001",
    role: "attendee",
    mintedAt: new Date("2024-02-28"),
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=400",
    hostName: "Sarah Chen",
  },
];

export const eventCategories = [
  "Conference",
  "Workshop",
  "Meetup",
  "Hackathon",
  "Exhibition",
  "Networking",
  "Concert",
  "Festival",
  "Other",
];
